# Generated by Django 2.2.6 on 2019-10-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posting',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='posting',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='like_users',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
